# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dylanr96
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getMessages:
    handler: functions/GetMessages.handler
    events:
      - httpApi:
          path: "/message"
          method: GET
  getMessage:
    handler: functions/GetMessage.handler
    events:
      - httpApi:
          path: "/message/{username}"
          method: GET
  editMessage:
    handler: functions/EditMessage.handler
    events:
      - httpApi:
          path: "/message"
          method: PUT
  addMessage:
    handler: functions/AddMessage.handler
    events:
      - httpApi:
          path: "/message"
          method: POST
resources:
  Resources:
    messageBoardDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MessageBoard
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
